name: Build and Release APK

on:
  push:
    branches:
      - master # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Regenerate Keystore
      run: |
       keytool -genkey -v -keystore /home/runner/work/reactmap-android/reactmap-android/keystore.jks \
       -keyalg RSA -keysize 2048 -validity 10000 -alias ${{ secrets.KEY_ALIAS }} \
       -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} \
       -dname "CN=Aco, OU=Pogofuerth, O=Pogofuerth, L=DE, ST=BY, C=DE"
    
    - name: Check if keystore is available
      run: ls -a /home/runner/work/reactmap-android/reactmap-android/keystore.jks

    - name: Make Gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Sign APK and create release
      run: |
        cd /home/runner/work/reactmap-android/reactmap-android/
        ./gradlew assembleRelease
        jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
        -keystore keystore.jks \
        -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
        -keypass ${{ secrets.KEY_PASSWORD }} \
        app/build/outputs/apk/release/app-release.apk ${{ secrets.KEY_ALIAS }}
    - name: List APK directory - build
      run: ls -R /home/runner/work/reactmap-android/reactmap-android/app/build/outputs/apk/release/
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Reactmap-android
        path: /home/runner/work/reactmap-android/reactmap-android/app/build/outputs/apk/release/app-release.apk
